# 端口
server:
  port: 20704

spring:
#  application:
#    name: payment-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_springcloud?allowPublicKeyRetrieval=true&useSSL=true
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true


